---
- name: Setting up variables
  set_fact:
    mysql_rds: ${db_RDS}  
    mysql_db: ${db_name}
    mysql_user: ${db_username}
    mysql_password: ${db_user_password}

- name: Copy wp-config to host webserver
  ansible.builtin.template:
    src: "wp-config.php.j2"
    dest: "/var/www/html/wp-config.php"

  notify: 
      - restart httpd service

- name: set permissions (changing ownership)
  command: "chown -R ec2-user:apache /var/www/html"